!theme mono
hide circle
hide empty methods
hide footbox

skinparam linetype ortho
skinparam Shadowing false
skinparam RoundCorner 0
skinparam Padding 3
skinparam dpi 110
skinparam DefaultFontName "Helvetica, Arial, sans-serif"
skinparam DefaultFontSize 13
skinparam WrapWidth 0
skinparam Guillemet false

' Classes
skinparam ClassBorderRoundCorner 0
skinparam ClassBorderThickness 1
skinparam ClassFontSize 13
skinparam ClassAttributeIconSize 0
skinparam ClassHeaderIconSize 0
skinparam ClassAttributeFontSize 12
skinparam ClassMethodFontSize 12
skinparam UseUML2ForComponent false

' Interfaces
skinparam InterfaceBorderThickness 1
skinparam InterfaceFontSize 13
skinparam InterfaceBorderRoundCorner 0
skinparam LollipopColor black

' Abstract classes / Enums
skinparam AbstractClassFontStyle italic
skinparam EnumBorderRoundCorner 0

' Packages
skinparam PackageStyle rectangle
skinparam PackageBorderThickness 1
skinparam PackageBorderRoundCorner 0
skinparam PackageFontSize 13

' Notes
skinparam NoteBorderRoundCorner 0
skinparam NoteFontSize 12

' Associations
skinparam AssociationFontSize 11

' Sequence Diagram tweaks
skinparam sequenceMessageAlign center
skinparam BoxPadding 0

' Sequence participants / actors
skinparam ActorBorderThickness 1.5
skinparam ParticipantBorderThickness 1.5